// Top-level build file where you can add configuration options common to all sub-projects/modules.\n\nplugins {\n    id 'com.android.application' version '7.4.0' apply false\n    id 'com.android.library' version '7.4.0' apply false\n}\n\ntask clean(type: Delete) {\n    delete rootProject.buildDir\n}\n\nallprojects {\n    repositories {\n        google()\n        mavenCentral()\n    }\n}\n\next {\n    compileSdkVersion = 33\n    targetSdkVersion = 33\n    minSdkVersion = 24\n    versionCode = 1\n    versionName = \"0.1.0-alpha\"\n}\n